### ISSUE TITLE
Where's the game?

### ISSUE THREAD

**Issue by Wuzzy2** [fastrgv/AdaVenture#1]
Umm, where's the _actual game_? I don't see anything here besides a readme file and some screenshots.

**Comment by fastrgv** [comment]
Look under "code", then "releases", then you should see "av16sep16.tar.gz".  Click on that to download.  I'll be uploading a new release very soon with a much better maze.
Rod

**Comment by Wuzzy2** [comment]
Okay. Do you use version control for your software source code? Then it would help if it is directly visible in GitHub, rather than in Releases.

Also, it might help to put a link into the readme file. Just saying. ;-)

**Comment by fastrgv** [comment]
If I ever find another Ada programmer interested in co-developing, I might try github version control for source.  But you should know that I have been screwed by V.C. systems before (clearcase) so I am not convinced they are as fullproof as they advertise.

**Comment by Wuzzy2** [comment]
Okay. I understand. Have fun coding! :-)
